"""Report generation: markdown index + JSON inventory.

The markdown output is designed to drop straight into a ``local-tool-reuse``
style index skill: one section per category, a summary table, and per-skill
reasons so a human (or an agent) can act on it without re-deriving anything.
"""

from __future__ import annotations

import datetime as _dt
import json
from collections import Counter
from pathlib import Path

from .differ import sync_state
from .model import CATEGORIES, ScanResult, Skill

_CATEGORY_TITLES = {
    "A": "A — 可直接复制使用（无平台绑定，依赖齐全）",
    "B": "B — 可迁移，但缺外部依赖（按需补齐）",
    "C": "C — 方法论可复用，文本须为目标平台改写",
    "D": "D — 平台私有，不要迁移",
    "?": "? — 未分类",
}

_CATEGORY_TITLES_EN = {
    "A": "A — portable (no platform bindings, all deps present)",
    "B": "B — portable but missing external dependencies",
    "C": "C — methodology reusable, text must be rewritten for the target",
    "D": "D — platform-private, do not migrate",
    "?": "? — unclassified",
}


def to_json(result: ScanResult) -> str:
    payload = {
        "generated_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "roots": [{"label": lbl, "path": str(p)} for lbl, p in result.roots_scanned],
        "errors": result.errors,
        "counts": dict(Counter(s.category for s in result.skills)),
        "skills": [
            {
                "name": s.name,
                "source": s.source,
                "path": str(s.path),
                "category": s.category,
                "category_reason": s.category_reason,
                "missing_deps": s.missing_deps,
                "sync": sync_state(s),
                "synced_to": str(s.synced_to) if s.synced_to else None,
                "description": s.description[:200],
                "warnings": s.parse_warnings,
            }
            for s in sorted(result.skills, key=lambda x: (x.source, x.name))
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def to_markdown(result: ScanResult, *, lang: str = "zh") -> str:
    titles = _CATEGORY_TITLES if lang == "zh" else _CATEGORY_TITLES_EN
    by_cat = result.by_category()
    counts = Counter(s.category for s in result.skills)
    sync_counts = Counter(sync_state(s) for s in result.skills)

    lines: list[str] = []
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines.append("# Skill 迁移索引（自动生成）" if lang == "zh" else "# Skill migration index (generated)")
    lines.append("")
    lines.append(
        f"> 由 `skillsync` 生成于 {stamp} — 不要手工编辑此文件。"
        if lang == "zh"
        else f"> Generated by `skillsync` at {stamp} — do not edit by hand."
    )
    lines.append("")

    lines.append("## 概览" if lang == "zh" else "## Overview")
    lines.append("")
    lines.append("| 指标 | 数量 |")
    lines.append("|---|---|")
    lines.append(f"| 扫描到 skill 总数 | {len(result.skills)} |")
    for cat in CATEGORIES:
        lines.append(f"| {cat} 类 | {counts.get(cat, 0)} |")
    lines.append(f"| 已同步（identical） | {sync_counts.get('identical', 0)} |")
    lines.append(f"| 内容漂移（drifted） | {sync_counts.get('drifted', 0)} |")
    lines.append(f"| 目标缺失（missing） | {sync_counts.get('missing', 0)} |")
    lines.append("")

    lines.append("## 扫描根目录" if lang == "zh" else "## Roots scanned")
    lines.append("")
    for label, path in result.roots_scanned:
        lines.append(f"- `{label}` → `{path}`")
    if result.errors:
        lines.append("")
        lines.append("### 警告" if lang == "zh" else "### Warnings")
        for err in result.errors:
            lines.append(f"- {err}")
    lines.append("")

    for cat in (*CATEGORIES, "?"):
        skills = by_cat.get(cat) or []
        if not skills:
            continue
        lines.append(f"## {titles[cat]}（{len(skills)}）")
        lines.append("")
        lines.append("| skill | 来源 | 同步状态 | 判定依据 / 缺失依赖 |")
        lines.append("|---|---|---|---|")
        for s in sorted(skills, key=lambda x: x.name):
            reason = s.category_reason.replace("|", "\\|")
            if s.missing_deps:
                reason += " — 缺: " + ", ".join(f"`{d}`" for d in s.missing_deps)
            state = sync_state(s)
            mark = {"identical": "✅", "drifted": "⚠️ 漂移", "missing": "—"}.get(state, state)
            lines.append(f"| `{s.name}` | {s.source} | {mark} | {reason} |")
        lines.append("")

    drifted = [s for s in result.skills if sync_state(s) == "drifted"]
    if drifted:
        lines.append("## 漂移明细（源与目标内容不一致）" if lang == "zh" else "## Drift details")
        lines.append("")
        for s in sorted(drifted, key=lambda x: x.name):
            lines.append(f"- `{s.name}`: 源 `{s.path}` ≠ 目标 `{s.synced_to}`")
        lines.append("")

    return "\n".join(lines)


def write_outputs(result: ScanResult, out_dir: Path, *, lang: str = "zh") -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "INDEX.md"
    json_path = out_dir / "inventory.json"
    md_path.write_text(to_markdown(result, lang=lang), encoding="utf-8")
    json_path.write_text(to_json(result), encoding="utf-8")
    return [md_path, json_path]
